title: Blink, pulse and cycle an RGB LED
hero_image: images/banner.png
description: pico-rgb-led-blink-pulse-cycle description
version: 4
listed: false
copyedit: false
last_tested: "2022-03-08"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
